function createfigure4(X1, YMatrix1)
%CREATEFIGURE4(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 14-Aug-2020 12:09:19

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1,'Parent',axes1);
set(plot1(1),'DisplayName','N=30,T=50','Marker','*');
set(plot1(2),'DisplayName','N=30,T=100','Marker','o');
set(plot1(3),'DisplayName','N=30,T=200','Marker','^');
set(plot1(4),'DisplayName','N=50,T=50','Marker','diamond');
set(plot1(5),'DisplayName','N=50,T=100','Marker','x');
set(plot1(6),'DisplayName','N=50,T=200','Marker','square');

% Create ylabel
ylabel({'Empirical size(%)'});

% Create xlabel
xlabel({'Sparseness of the standardized weights matrix (j ahead and j behind)'});

% Create title
title({'Case II: intercept only theta=0.75'});

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 0.2]);
box(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.690721649484536 0.649684242001472 0.192078133478025 0.172732696897375],...
    'EdgeColor',[1 1 1]);

