function plotstability(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 04-Aug-2020 23:48:36

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1,'Parent',axes1);
set(plot1(1),'DisplayName','1 percentile theta=0.8','Marker','*');
set(plot1(2),'DisplayName','1 percentile theta=0.8','Marker','*');
set(plot1(3),'DisplayName','1 percentile theta=0.8','Marker','*');
set(plot1(4),'DisplayName','5 percentile theta=0.4','Marker','diamond',...
    'LineStyle','-.');
set(plot1(5),'DisplayName','5 percentile theta=0.4','Marker','diamond',...
    'LineStyle','-.');
set(plot1(6),'DisplayName','5 percentile theta=0.4','Marker','diamond',...
    'LineStyle','-.');
set(plot1(7),'DisplayName','10 percentile theta=0.2','Marker','o',...
    'LineStyle','--');
set(plot1(8),'DisplayName','10 percentile theta=0.2','Marker','o',...
    'LineStyle','--');
set(plot1(9),'DisplayName','10 percentile theta=0.2','Marker','o',...
    'LineStyle','--');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-1.68 -1.4]);
box(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.146500271296799 0.643047528220652 0.282691264243082 0.255966587112172]);

