function [results] = secips(N,T,n,theta)
% SECIPS monte carlo simulations of spacial error model
% y is generated by Baltagi 2007, equation 10,12
% secips is caculated by average t statistics of lambda
% info.model=0 for individual intercepts
% info.model=1 for individual deterministic trends
W=head(N,n);
%% generate y
T0=40;
y=zeros(N,T+T0);
    sigma=zeros(1,N);
    epsilon=zeros(1,N);
for t=1:T+T0
    for i=1:N
    sigma(i)=rand+0.5;
    epsilon(i)=normrnd(0,sigma(i)^0.5);
    end
    u=(eye(N)-theta*W)^(-1)*epsilon';
    y(:,t+1)= y(:,t)+u;
end

%% estimate gamma
t=zeros(N,1);
tau=ones(T,1);
MT=eye(T)-tau*(tau'*tau)^(-1)*tau';
sigmahat=zeros(N,1);
for i=1:N
    yt=y(i,T0+2:T+T0+1)';
    ylag=y(i,T0+1:T+T0)';
    deltay=yt-ylag;
    sigmahat(i)=deltay'*MT*deltay/(T-2);
    t(i)=deltay'*MT*ylag/(sigmahat(i)*ylag'*MT*ylag)^0.5;
end




results.secips=mean(t);
end

